version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf

    cron:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: helloworld
        volumes:
            - ./data:/tmp/data/

    php:
#        build:
#            context: .
#            dockerfile: ./Dockerfile
        image: helloworld
        volumes:
            - ./code:/code
            - /tmp/data:/tmp/data/
#        command: /bin/bash -c 'exec /usr/sbin/php-fpm -F'
        command: ["/usr/sbin/php-fpm", "-F", "-R"]
#        command: php-fpm -F

    phpfpm:
        image: php:fpm
        volumes:
            - ./code:/code
            - /tmp/data:/tmp/data/
